# Form implementation generated from reading ui file 'c:\Users\IdeaPad\OneDrive\Documenti\itspython\progetto_swtelemedLogin\login.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usr = QtWidgets.QLineEdit(self.centralwidget)
        self.usr.setGeometry(QtCore.QRect(290, 80, 171, 22))
        self.usr.setObjectName("usr")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 120, 171, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.accedi = QtWidgets.QPushButton(self.centralwidget)
        self.accedi.setGeometry(QtCore.QRect(310, 160, 93, 28))
        self.accedi.setObjectName("accedi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usr.setPlaceholderText(_translate("MainWindow", "               user"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "password"))
        self.accedi.setText(_translate("MainWindow", "accedi"))
